services:
  web:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: django-app
    environment:
      PRODUCTION: ${PRODUCTION}
    env_file:
      - ecommerce/utils/.env
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_NAME: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 30s
      retries: 3

