services:
  web:
    build:
      context: .
      dockerfile: backend/Dockerfile
      secrets:
      - db_password
      - secret_key
    container_name: django-app
    environment:
      PRODUCTION: ${PRODUCTION}
    env_file:
      - utils/environments/db.env
      - utils/environments/app.env
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    container_name: database
    ports:
      - "5432:5432"
    env_file:
      - utils/environments/db.env
    secrets:
      - db_password
    environment:
      POSTGRES_NAME: ${DB_NAME:-postgres}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: /run/secrets/db_password #${DB_PASSWORD:-postgres}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 30s
      retries: 3


secrets:
  db_password:
    file: utils/security/db_password.txt
  secret_key:
    environment: SECRET_KEY